import { CalendarPlus, Copy, Mail, RefreshCw, Search, Send, XCircle } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { useAuth } from '../auth/AuthContext'

const emptyForm = {
  candidateId: '', candidateName: '', candidateEmail: '', companyName: '', position: 'Software Developer',
  startTime: '', endTime: '', skills: '', experienceLevel: 'intermediate', focusAreas: 'technical,problem-solving',
  allowCodeEditor: true, customQuestions: '', notes: ''
}
const statusOptions = ['all', 'scheduled', 'active', 'completed', 'expired', 'cancelled']
const formatDateTime = value => value ? new Date(value).toLocaleString() : '—'
const statusClass = status => ({ scheduled: 'bg-blue-50 text-blue-700 border-blue-200', active: 'bg-emerald-50 text-emerald-700 border-emerald-200', completed: 'bg-slate-100 text-slate-700 border-slate-200', expired: 'bg-amber-50 text-amber-700 border-amber-200', cancelled: 'bg-red-50 text-red-700 border-red-200' }[status] || 'bg-slate-100 text-slate-600 border-slate-200')
function durationMinutes(startTime, endTime) { const start = new Date(startTime); const end = new Date(endTime); return Number.isNaN(start.getTime()) || Number.isNaN(end.getTime()) || end <= start ? null : Math.ceil((end - start) / 60000) }

export default function SessionScheduler() {
  const { apiFetch, user } = useAuth()
  const [sessions, setSessions] = useState([]); const [formData, setFormData] = useState(emptyForm)
  const [loading, setLoading] = useState(false); const [loadingSessions, setLoadingSessions] = useState(true); const [actionId, setActionId] = useState('')
  const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [inviteUrl, setInviteUrl] = useState('')
  const [statusFilter, setStatusFilter] = useState('all'); const [query, setQuery] = useState('')

  const loadSessions = useCallback(async () => { setLoadingSessions(true); try { setError(''); const params = new URLSearchParams(); if (statusFilter !== 'all') params.set('status', statusFilter); const data = await apiFetch(`/api/scheduled-sessions/list${params.toString() ? `?${params}` : ''}`); setSessions(data.sessions || []) } catch (err) { setError(err.message) } finally { setLoadingSessions(false) } }, [apiFetch, statusFilter])
  useEffect(() => { loadSessions() }, [loadSessions])
  const visibleSessions = useMemo(() => { const value = query.trim().toLowerCase(); return value ? sessions.filter(session => [session.candidateName, session.candidateId, session.candidateEmail, session.position, session.sessionId].filter(Boolean).some(item => String(item).toLowerCase().includes(value))) : sessions }, [query, sessions])
  const duration = useMemo(() => durationMinutes(formData.startTime, formData.endTime), [formData.endTime, formData.startTime])
  const change = event => { const { name, value, type, checked } = event.target; setFormData(previous => ({ ...previous, [name]: type === 'checkbox' ? checked : value })) }

  const schedule = async event => {
    event.preventDefault(); setError(''); setSuccess(''); setInviteUrl('')
    const minutes = durationMinutes(formData.startTime, formData.endTime); const end = new Date(formData.endTime)
    if (!minutes) return setError('End time must be after start time.')
    if (end <= new Date()) return setError('Interview end time must be in the future.')
    if (minutes < 15 || minutes > 240) return setError('Interview duration must be between 15 and 240 minutes.')
    setLoading(true)
    try {
      const data = await apiFetch('/api/scheduled-sessions/create', { method: 'POST', body: JSON.stringify({ ...formData, skills: formData.skills.split(',').map(v => v.trim()).filter(Boolean), focusAreas: formData.focusAreas.split(',').map(v => v.trim()).filter(Boolean), customQuestions: formData.customQuestions.split('\n').map(v => v.trim()).filter(Boolean), accessWindow: { beforeStart: 15, afterEnd: 15 }, timeZone: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC' }) })
      setSuccess(`Interview scheduled for ${data.session.candidateName}. Copy or email the secure link before the interview starts.`); setInviteUrl(data.session.accessUrl || ''); setFormData(emptyForm); await loadSessions()
    } catch (err) { setError(err.message) } finally { setLoading(false) }
  }
  const copyInvite = async () => { try { await navigator.clipboard.writeText(inviteUrl); setSuccess('Secure interview link copied.') } catch { setError('Automatic copy failed. Select the link and copy it manually.') } }
  const emailAction = async (session, reminder = false) => {
    if (session.status !== 'scheduled') return setError('Invite links cannot be rotated after an interview has started.')
    setActionId(`${reminder ? 'reminder' : 'invite'}:${session.sessionId}`); setError(''); setSuccess('')
    try { const data = await apiFetch(reminder ? '/api/email/send-reminder' : '/api/email/send-session-invite', { method: 'POST', body: JSON.stringify({ candidateId: session.candidateId, sessionId: session.sessionId, ...(reminder ? { minutesUntilStart: 15 } : {}) }) }); setInviteUrl(data.data?.sessionUrl || ''); setSuccess(`${reminder ? 'Reminder' : 'Invite'} sent to ${data.data?.candidateEmail || session.candidateEmail}. The previous link is now invalid.`); await loadSessions() } catch (err) { setError(err.message) } finally { setActionId('') }
  }
  const cancel = async session => { if (!window.confirm(`Cancel the interview for ${session.candidateName}?`)) return; setActionId(`cancel:${session.sessionId}`); try { await apiFetch(`/api/scheduled-sessions/update/${encodeURIComponent(session.sessionId)}`, { method: 'PUT', body: JSON.stringify({ status: 'cancelled' }) }); setSuccess(`Interview for ${session.candidateName} was cancelled.`); await loadSessions() } catch (err) { setError(err.message) } finally { setActionId('') } }

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue-600">Interview operations</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">Interviews</h1><p className="mt-2 text-sm text-slate-500">Schedule signed sessions, deliver secure links, and manage live interview state.</p></div><button onClick={loadSessions} disabled={loadingSessions} className="inline-flex items-center justify-center gap-2 rounded-lg border bg-white px-4 py-2.5 text-sm font-medium disabled:opacity-50"><RefreshCw size={16} className={loadingSessions ? 'animate-spin' : ''} /> Refresh</button></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}{success && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700">{success}</div>}
    {inviteUrl && <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-blue-950">Current secure candidate link</p><p className="text-xs text-blue-700">Treat this link like a password. A successful resend invalidates the previous link.</p></div><button onClick={copyInvite} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-3 py-2 text-sm font-medium text-white"><Copy size={15} /> Copy</button></div><input readOnly value={inviteUrl} className="mt-3 w-full rounded-lg border border-blue-200 bg-white px-3 py-2 text-xs" /></div>}
    <div className="grid items-start gap-6 xl:grid-cols-[0.8fr_1.2fr]">
      <form onSubmit={schedule} className="space-y-4 rounded-xl border bg-white p-5 shadow-sm xl:sticky xl:top-24"><div className="flex items-center gap-2"><CalendarPlus size={19} className="text-blue-600" /><div><h2 className="font-semibold">Schedule interview</h2><p className="text-xs text-slate-500">Signed in as {user?.name}</p></div></div>
        <div className="grid gap-3 sm:grid-cols-2"><input required name="candidateId" value={formData.candidateId} onChange={change} placeholder="Candidate ID" className="rounded-lg border px-3 py-2.5 text-sm" /><input required name="candidateName" value={formData.candidateName} onChange={change} placeholder="Candidate name" className="rounded-lg border px-3 py-2.5 text-sm" /><input type="email" name="candidateEmail" value={formData.candidateEmail} onChange={change} placeholder="Candidate email" className="rounded-lg border px-3 py-2.5 text-sm" /><input name="companyName" value={formData.companyName} onChange={change} placeholder="Company" className="rounded-lg border px-3 py-2.5 text-sm" /></div>
        <input name="position" value={formData.position} onChange={change} placeholder="Position / role" className="w-full rounded-lg border px-3 py-2.5 text-sm" /><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-medium">Start time<input required type="datetime-local" name="startTime" value={formData.startTime} onChange={change} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm" /></label><label className="text-xs font-medium">End time<input required type="datetime-local" name="endTime" value={formData.endTime} onChange={change} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm" /></label></div><p className="text-xs text-slate-500">Calculated duration: {duration ? `${duration} minutes` : '—'}</p>
        <div className="grid gap-3 sm:grid-cols-2"><select name="experienceLevel" value={formData.experienceLevel} onChange={change} className="rounded-lg border px-3 py-2.5 text-sm"><option value="junior">Junior</option><option value="intermediate">Intermediate</option><option value="senior">Senior</option></select><input name="focusAreas" value={formData.focusAreas} onChange={change} placeholder="Focus areas" className="rounded-lg border px-3 py-2.5 text-sm" /></div><input name="skills" value={formData.skills} onChange={change} placeholder="Skills: React, Node.js, C++" className="w-full rounded-lg border px-3 py-2.5 text-sm" /><textarea name="customQuestions" value={formData.customQuestions} onChange={change} rows="3" placeholder="Optional custom questions, one per line" className="w-full rounded-lg border px-3 py-2.5 text-sm" /><textarea name="notes" value={formData.notes} onChange={change} rows="2" placeholder="Internal recruiter notes" className="w-full rounded-lg border px-3 py-2.5 text-sm" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="allowCodeEditor" checked={formData.allowCodeEditor} onChange={change} /> Enable coding exercise</label><button disabled={loading} className="w-full rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{loading ? 'Scheduling…' : 'Schedule secure interview'}</button>
      </form>
      <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 md:flex-row"><div className="relative flex-1"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search candidate, email, role, session…" className="w-full rounded-lg border py-2 pl-9 pr-3 text-sm" /></div><select value={statusFilter} onChange={e => setStatusFilter(e.target.value)} className="rounded-lg border px-3 py-2 text-sm">{statusOptions.map(status => <option key={status} value={status}>{status === 'all' ? 'All statuses' : status}</option>)}</select></div><div className="divide-y">{visibleSessions.map(session => { const canInvite = session.status === 'scheduled'; const canCancel = ['scheduled', 'active'].includes(session.status); const hasEmail = Boolean(session.candidateEmail); return <article key={session.sessionId} className="p-4 sm:p-5"><div className="flex justify-between gap-3"><div className="min-w-0"><p className="truncate font-semibold">{session.candidateName}</p><p className="truncate text-sm text-slate-500">{session.position || 'Interview'} · {session.candidateEmail || session.candidateId}</p></div><span className={`h-fit rounded-full border px-2.5 py-1 text-xs capitalize ${statusClass(session.status)}`}>{session.status}</span></div><div className="mt-4 grid gap-2 text-xs text-slate-500 sm:grid-cols-2"><p>Start: {formatDateTime(session.startTime)}</p><p>End: {formatDateTime(session.endTime)}</p><p className="truncate">Session: {session.sessionId}</p><p>Failed access: {session.accessAttempts || 0}</p></div>{(canInvite || canCancel) && <div className="mt-4 flex flex-wrap gap-2">{canInvite && <><button disabled={!hasEmail || Boolean(actionId)} onClick={() => emailAction(session)} className="inline-flex items-center gap-1 rounded-md border border-blue-200 px-2.5 py-1.5 text-xs text-blue-700 disabled:opacity-40"><Mail size={14} /> Send invite</button><button disabled={!hasEmail || Boolean(actionId)} onClick={() => emailAction(session, true)} className="inline-flex items-center gap-1 rounded-md border px-2.5 py-1.5 text-xs disabled:opacity-40"><Send size={14} /> Reminder</button></>}{canCancel && <button disabled={Boolean(actionId)} onClick={() => cancel(session)} className="inline-flex items-center gap-1 rounded-md border border-red-200 px-2.5 py-1.5 text-xs text-red-700 disabled:opacity-40"><XCircle size={14} /> Cancel</button>}</div>}</article>})}{!loadingSessions && !visibleSessions.length && <p className="py-14 text-center text-sm text-slate-500">No interviews match the filters.</p>}{loadingSessions && <p className="py-14 text-center text-sm text-slate-500">Loading interviews…</p>}</div></section>
    </div>
  </div>
}