import { Download, Search, ShieldAlert, X } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { useAuth } from '../auth/AuthContext'
import config from '../config'

const formatDate = value => value ? new Date(value).toLocaleString() : '—'
const prettyType = value => String(value || '').replace(/_/g, ' ')

export default function ResultsPage() {
  const { apiFetch, token } = useAuth()
  const [results, setResults] = useState([]); const [query, setQuery] = useState(''); const [search, setSearch] = useState(''); const [page, setPage] = useState(1); const [pages, setPages] = useState(1); const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [detail, setDetail] = useState(null); const [detailLoading, setDetailLoading] = useState(false)

  const load = useCallback(async () => { setLoading(true); try { setError(''); const params = new URLSearchParams({ page: String(page), limit: '25' }); if (search) params.set('q', search); const data = await apiFetch(`/api/interview/results?${params}`); setResults(data.results || []); setPages(data.pages || 1); setTotal(data.total || 0) } catch (err) { setError(err.message) } finally { setLoading(false) } }, [apiFetch, page, search])
  useEffect(() => { load() }, [load])

  const openDetail = async result => { if (!result.fileName) return; setDetailLoading(true); setError(''); try { const data = await apiFetch(`/api/interview/results/${encodeURIComponent(result.fileName)}`); setDetail(data.data) } catch (err) { setError(err.message) } finally { setDetailLoading(false) } }
  const exportCsv = async () => { try { setError(''); const params = new URLSearchParams(); if (search) params.set('q', search); const response = await fetch(`${config.AI_BACKEND_URL}/api/interview/results/export.csv?${params}`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) { const data = await response.json().catch(() => ({})); throw new Error(data.error || 'Failed to export results') } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `interview-results-${new Date().toISOString().slice(0, 10)}.csv`; document.body.appendChild(anchor); anchor.click(); anchor.remove(); URL.revokeObjectURL(url) } catch (err) { setError(err.message) } }

  const transcript = detail ? (Array.isArray(detail.fullTranscript) ? detail.fullTranscript : (Array.isArray(detail.transcript) ? detail.transcript : [])) : []
  const integrity = detail?.integrity

  return <div className="space-y-6">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-blue-600">Assessment history</p><h1 className="mt-1 text-3xl font-semibold text-slate-950">Interview results</h1><p className="mt-2 text-sm text-slate-500">Review technical evaluation, transcript, and separate client-side integrity signals.</p></div><button onClick={exportCsv} className="inline-flex items-center justify-center gap-2 rounded-lg border bg-white px-4 py-2.5 text-sm font-medium"><Download size={17} /> Export CSV</button></div>
    {error && <div className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}

    <div className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row sm:items-center sm:justify-between"><form onSubmit={event => { event.preventDefault(); setPage(1); setSearch(query.trim()) }} className="flex w-full gap-2 sm:max-w-xl"><div className="relative flex-1"><Search size={17} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search candidate, role, session…" className="w-full rounded-lg border py-2.5 pl-9 pr-3 text-sm" /></div><button className="rounded-lg border px-4 py-2 text-sm">Search</button></form><span className="text-sm text-slate-500">{total} results</span></div>
      <div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs uppercase text-slate-500"><tr><th className="px-5 py-3">Candidate</th><th className="px-5 py-3">Interview</th><th className="px-5 py-3">Activity</th><th className="px-5 py-3">Score</th><th className="px-5 py-3">Date</th><th className="px-5 py-3"></th></tr></thead><tbody className="divide-y">{results.map((result, index) => <tr key={`${result.fileName || result.sessionId}-${index}`} className="hover:bg-slate-50"><td className="px-5 py-4"><p className="font-medium">{result.candidateName || 'Candidate'}</p><p className="text-xs text-slate-500">{result.candidateEmail || result.sessionId || '—'}</p></td><td className="px-5 py-4 text-slate-600">{result.position || '—'}</td><td className="px-5 py-4 text-slate-500">{result.questionsAsked || 0} questions · {result.codingTestsCompleted || 0} coding</td><td className="px-5 py-4">{result.overallScore !== null && result.overallScore !== undefined ? <span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">{result.overallScore}</span> : <span className="text-slate-400">—</span>}</td><td className="px-5 py-4 text-slate-500">{formatDate(result.date)}</td><td className="px-5 py-4 text-right"><button disabled={!result.fileName || detailLoading} onClick={() => openDetail(result)} className="rounded-md border px-2.5 py-1.5 text-xs disabled:opacity-40">Review</button></td></tr>)}</tbody></table>{loading && <div className="py-14 text-center text-sm text-slate-500">Loading results…</div>}{!loading && !results.length && <div className="py-14 text-center text-sm text-slate-500">No interview results found.</div>}</div>
      <div className="flex items-center justify-between border-t px-5 py-3 text-sm"><button disabled={page <= 1} onClick={() => setPage(value => value - 1)} className="rounded-md border px-3 py-1.5 disabled:opacity-40">Previous</button><span className="text-slate-500">Page {page} of {pages}</span><button disabled={page >= pages} onClick={() => setPage(value => value + 1)} className="rounded-md border px-3 py-1.5 disabled:opacity-40">Next</button></div>
    </div>

    {detail && <div className="fixed inset-0 z-50 flex justify-end"><button aria-label="Close" onClick={() => setDetail(null)} className="absolute inset-0 bg-slate-950/40" /><aside className="relative h-full w-full max-w-2xl overflow-auto bg-white shadow-2xl"><div className="sticky top-0 z-10 flex items-start justify-between border-b bg-white px-6 py-4"><div><p className="text-xs uppercase tracking-wide text-blue-600">Interview report</p><h2 className="mt-1 text-xl font-semibold">{detail.candidateInfo?.name || detail.candidateName || 'Candidate'}</h2><p className="text-sm text-slate-500">{detail.candidateInfo?.position || detail.position || detail.sessionId || ''}</p></div><button onClick={() => setDetail(null)} className="p-2"><X size={20} /></button></div><div className="space-y-6 p-6">
      <div className="grid gap-3 sm:grid-cols-3"><div className="rounded-xl border bg-slate-50 p-4"><p className="text-xs text-slate-400">Duration</p><p className="mt-1 font-semibold">{detail.interviewDetails?.duration ?? '—'}</p></div><div className="rounded-xl border bg-slate-50 p-4"><p className="text-xs text-slate-400">Questions</p><p className="mt-1 font-semibold">{detail.interviewDetails?.totalQuestions ?? '—'}</p></div><div className="rounded-xl border bg-slate-50 p-4"><p className="text-xs text-slate-400">Coding tests</p><p className="mt-1 font-semibold">{detail.interviewDetails?.codingTestsCompleted ?? '—'}</p></div></div>
      {(detail.evaluation || detail.summary || detail.recommendation) && <section><h3 className="mb-2 font-semibold">Technical evaluation</h3><pre className="overflow-auto whitespace-pre-wrap rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(detail.evaluation || detail.summary || { recommendation: detail.recommendation }, null, 2)}</pre></section>}
      {integrity && <section className="rounded-xl border border-amber-200 bg-amber-50 p-4"><div className="flex gap-3"><ShieldAlert className="shrink-0 text-amber-700" size={20} /><div><h3 className="font-semibold text-amber-950">Integrity signals</h3><p className="mt-1 text-xs leading-5 text-amber-800">{integrity.notice || 'Client-side signals are review aids and are not part of the AI technical score.'}</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-lg bg-white/70 p-3"><p className="text-xs text-amber-700">Signals</p><p className="mt-1 font-semibold">{integrity.totalEvents || 0}</p></div><div className="rounded-lg bg-white/70 p-3"><p className="text-xs text-amber-700">Flagged events</p><p className="mt-1 font-semibold">{integrity.flaggedEvents || 0}</p></div></div>{Array.isArray(integrity.events) && integrity.events.length > 0 && <details className="mt-3 rounded-lg border border-amber-200 bg-white/70"><summary className="cursor-pointer px-3 py-2 text-sm font-medium">Review event timeline</summary><div className="max-h-72 space-y-2 overflow-auto border-t p-3">{integrity.events.map((event, index) => <div key={`${event.receivedAt || event.observedAt}-${index}`} className="text-xs"><span className="font-semibold capitalize">{prettyType(event.type)}</span><span className="ml-2 text-slate-500">{formatDate(event.observedAt || event.receivedAt)}</span></div>)}</div></details>}</section>}
      {transcript.length > 0 && <section><h3 className="mb-3 font-semibold">Transcript</h3><div className="space-y-2">{transcript.map((item, index) => <div key={item.sequence || index} className="rounded-lg border bg-slate-50 p-3 text-sm"><p className="text-xs font-semibold uppercase text-slate-400">{item.role || item.speaker || 'message'}</p><p className="mt-1 whitespace-pre-wrap text-slate-700">{item.message || item.content || item.text || JSON.stringify(item)}</p></div>)}</div></section>}
      <section><h3 className="mb-2 font-semibold">Raw result data</h3><details className="rounded-xl border bg-slate-50"><summary className="cursor-pointer px-4 py-3 text-sm font-medium">Open technical payload</summary><pre className="max-h-[420px] overflow-auto whitespace-pre-wrap border-t p-4 text-xs">{JSON.stringify(detail, null, 2)}</pre></details></section>
    </div></aside></div>}
  </div>
}